# SPDX-FileCopyrightText: Maximilian Huber <maximilian.huber@tngtech.com>
# SPDX-FileCopyrightText: Helio Chissini de Castro <heliocastro@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

name: spdx/tools-java workflow
permissions:
  contents: write
env:
  SPDX_TOOLS_VERSION: 2.0.2
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - closed
  push:
    branches:
      - main
jobs:
  syntax-check-of-tag-value:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: "bootstrap spdx/tools-java"
        run: .github/workflows/scripts/spdx-tools-java-wrapper.sh bootstrap

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46.0.1
        with:
          fetch-depth: 50
          files: |
            **/*.spdx

      - name: "verify touched tag-value documents"
        run: .github/workflows/scripts/verify.sh ${{ steps.changed-files.outputs.all_changed_files }}
        if: github.event_name == 'pull_request'

      - name: "convert touched tag-value documents"
        run: .github/workflows/scripts/convert.sh ${{ steps.changed-files.outputs.all_changed_files }}
        if: github.event.pull_request.merged == true

      - uses: EndBug/add-and-commit@v9
        with:
          add: analysed-packages/
          message: "Auto generated by GitHub Action with SPDX Java Tools version ${{ env.SPDX_TOOLS_VERSION }}"
          committer_name: GitHub Actions
          committer_email: actions@github.com
          pull: --rebase --autostash origin main
          push: origin HEAD:main
        if: github.event.pull_request.merged == true

      - name: "verify all tag-value documents"
        run: .github/workflows/scripts/verify.sh all
        if: github.event_name != 'pull_request'
